# .github/workflows/friday_trigger.yml

name: Nifty Friday Trigger

# ──────────────────────────────────────────────────────────────────────────────
# 1) Schedule: run every Friday at 11:00 UTC (16:30 IST, after market close)
# ──────────────────────────────────────────────────────────────────────────────
on:
  schedule:
    - cron: '0 11 * * FRI'   # ──> every Friday at 11:00 UTC
  workflow_dispatch:        # allows manual runs via GitHub UI

jobs:
  run-trigger:
    runs-on: ubuntu-latest

    steps:
      # ────────────────────────────────────────────────────────────────────
      # 2) Step: Check out the repository so we can access our script/files
      # ────────────────────────────────────────────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4

      # ────────────────────────────────────────────────────────────────────
      # 3) Step: Set up Python (~3.10)
      # ────────────────────────────────────────────────────────────────────
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ────────────────────────────────────────────────────────────────────
      # 4) Step: Install dependencies from requirements.txt
      # ────────────────────────────────────────────────────────────────────
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ────────────────────────────────────────────────────────────────────
      # 5) Step: Run the Python trigger script, passing in our GitHub Secrets
      # ────────────────────────────────────────────────────────────────────
      - name: Run Friday Trigger Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python nifty_friday_trigger.py
